### ISSUE TITLE
from backdoor_utils import backdoor_inject

### ISSUE THREAD

**Issue by CooFlow** [jeongjin0/detector-cleanse#6]
Hi, I can't access to this code line:

`from backdoor_utils import backdoor_inject`

Can you please make this file available, via “drive” or any other way?

**Comment by jeongjin0** [comment]
Thank you for your question about the `backdoor_inject` function. Unfortunately, we cannot provide the specific implementation since this function represents the backdoor trigger injection method that was used during your model training process. As we don't know how you implemented the backdoor in your model, we cannot share the exact injection function.

For implementing your own backdoor_inject function, you might find it helpful to reference [mask backdoor](https://github.com/jeongjin0/invisible-backdoor-object-detection) and [untargeted backdoor](https://github.com/Chengxiao-Luo/Untargeted-Backdoor-Attack-against-Object-Detection) which contain relevant implementations. (backdoor attack on object detection)
